language: python

python:

  - "2.7"

services:
 
  - docker

before_install:
  - docker pull jozefiak/quantecon

before_script:
  - docker run --rm --name quantecon-docker -it -d -v ${TRAVIS_BUILD_DIR}:/home/jovyan/work jozefiak/quantecon /bin/bash

script: 

  - python hello.py
  - sudo docker exec quantecon-docker bash -c "cd work && make jupyter-tests"
  - docker exec quantecon-docker bash -c "cd work && bash run-notebook.sh arma.ipynb"